### ISSUE TITLE
Check and activate thumbnail generation

### ISSUE THREAD

**Issue by thinkh** [Caleydo/vega_clue#19]
After finishing #18 check if the thumbnails are still working with the Vega visualization. If not activate them again.

![search-result](https://user-images.githubusercontent.com/5851088/38017573-b7e43d7e-3272-11e8-87ee-f8e28c7016c6.png)

An alternative would be to use the Vega image export (see #7) and store the thumbnails in the provenance graph or elsewhere. However, this needs to be implemented then.

**Comment by sgratzl** [comment]
it doesn't work for me. I'm searching now for 2 hours for finding a solution for https://stackoverflow.com/questions/37883759/chrome-driver-handshake-failed-error-messages-selenium without success

**Comment by sgratzl** [comment]
minimal not working test setup. 

shell1:
```
docker-compose exec api bash

chromedriver --verbose
```

shell2
```
docker-compose exec api bash

python

from selenium import webdriver
driver = webdriver.Remote("http://127.0.0.1:9515", {'acceptInsecureCerts': True, 'chromeOptions': {'debuggerAddress': 'chrome:9222'}})
```

**Comment by thinkh** [comment]
It's working now as described in the PR https://github.com/Caleydo/vega_clue/pull/20#issuecomment-377554530.
