### ISSUE TITLE
Rename src/internal/spec.ts

### ISSUE THREAD

**Issue by ghost** [Caleydo/vega_clue#41]
Normally a spec.ts file is a test file (f.e. in AngularJS). We have the following regex to get all test files: testRegex: "(.*(test|spec))\\.(tsx?)$"

The src/internal/spec.ts would therefore be part of the tests, which is wrong.

Could you please rename the file (or we rename it for you) or are there problems, if we rename it in the repo?

**Comment by thinkh** [comment]
You are right. We can rename the file. No problem.

**Comment by thinkh** [comment]
I pushed the renaming directly to the `stoiber/test_with_jest` branch. [The CircleCI build succeeded](https://circleci.com/gh/Caleydo/vega_clue/183).
